#!/bin/bash

filter_hdr() {
	echo "** filtering $1"
	sed -E -f $mytemp/hdr_script < $1 >$mytemp/$2
}

filter_mak() {
	echo "** filtering $1"
	sed -E -f $mytemp/mak_script < $1 >$mytemp/$2
}

filter_shl() {
	echo "** filtering $1"
	sed -E -f $mytemp/shl_script < $1 >$mytemp/$2
}

do_filter() {
	$1 $2 update
	$1 ../trn-4.0-test77/$2 origin
	( cd $mytemp && diff -u -b -B origin update || echo "** ignored..." )
}

mytemp=$(mktemp -d)
trap "cd; rm -rf $mytemp" EXIT ERR

cat >$mytemp/hdr_script <<"EOF"
s/HAVE_/HAS_/
/\/\*[[:space:]]*#(undef|define)/d
/^#define/s,/\*.*\*/,,
s/\/\*\*\///g
s/[[:space:]]*$//
s/^(#define[[:space:]][[:alnum:]_]+)$/\1 1/
EOF

cat >$mytemp/mak_script <<"EOF"
/;[[:space:]]*\/bin\/sh[[:space:]]+$(srcdir)\/[[:alnum:]_]+\.SH/s,^,#,
s/[[:space:]]*$//
/^#/d
EOF

cat >$mytemp/shl_script <<"EOF"
s/\$(awk|basename|cat|cp|diff|echo|ed|expr|grep|mv|rm|sed|sleep|spell|test|who)/\1/g
s/[[:space:]]*$//
/^$/d
/^#/d
EOF

git clean -f -x -d
autoconf-252 || exit
YACC=byacc ./configure --prefix=/usr || exit

do_filter filter_hdr config.h
do_filter filter_mak Makefile
do_filter filter_shl Rnmail
do_filter filter_shl access.def
do_filter filter_shl Speller
do_filter filter_shl norm.saver
do_filter filter_shl mbox.saver
do_filter filter_shl makedir
do_filter filter_shl filexp
do_filter filter_shl Policy.sh

pwd
make -n -k
